# Generated by Django 5.1.2 on 2024-10-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expenseparticipant",
            name="user",
        ),
        migrations.AddField(
            model_name="expenseparticipant",
            name="username",
            field=models.CharField(default="Unknown", max_length=150),
            preserve_default=False,
        ),
    ]
