# Generated by Django 5.1.2 on 2024-10-21 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_expenseparticipant_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expenseparticipant",
            name="username",
        ),
        migrations.AddField(
            model_name="expenseparticipant",
            name="user",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
