# Generated by Django 5.1.2 on 2024-10-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_expenseparticipant_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="name",
            field=models.CharField(default="New Expanse", max_length=100),
        ),
    ]
